id: P94D449DC
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA00JR585
  instance_id: http://purl.bdrc.io/resource/IE00JR585
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - ཉང་སྐྱེས་སྣང་མཛད་རྡོ་རྗེའི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
  alt_title:
    en-x-mixed:
    - Ñaṅ-skyes Snaṅ-mdzad-rdo-rjeʼi gsuṅ rtsom phyogs bsgrigs /[sgrig pa po, Hūm̐-chen
      daṅ Ñi-zla].
    zh-hans:
    - 娘吉囊杂勒多吉文集
  author: http://purl.bdrc.io/resource/P6095
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    dbfe2b02d65849c6998a3924b219113c:
      title: པོད ༡་ཉང་སྐྱེས་སྣང་མཛད་རྡོ་རྗེའི་གསུང་རྩོམ་ཕྱོགས་བསྒྲིགས།
      volume_number: 1
      base_file: UT00JR585_I00KG03998_0000.txt
      reference: http://purl.bdrc.io/resource/VLE78C85B8FC5DEB5A
      image_group: I00KG03998
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W00JR585
  - http://purl.bdrc.io/resource/MW00JR585
  ocr_software: Namsel
created_at: '2021-12-22T10:14:17.300732'
last_modified_at: '2021-12-22T10:14:17.300739'
statistics:
  total_words: 138878
  total_non_words: 20923
quality:
  non_words_ratio: 0.15
